const express = require('express');
const app = express();

const PORT = 8081;

app.use(express.text({ type: '*/*' }));

const DATA = {
  users: [
    {
      uuid: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
      fullName: 'Игорь Слабухо',
      login: 'Gary',
      address: 'г. Минск, пр. Фрунзе, д. 80, кв. 20',
      website: 'onliner.by',
      isAdmin: true,
      organization: 'Tad',
      pass: 123,
    },
    {
      uuid: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
      fullName: 'Арсений Макаров',
      login: 'arseniy_m',
      address: 'г. Витебск, пр. Фрунзе, д. 80, кв. 20',
      website: 'makarov2.by',
      isAdmin: false,
      organization: 'ООО «ВитебскФарм»',
      pass: null,
    },
    {
      uuid: '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
      fullName: 'Мира Григорьева',
      login: 'mira_g',
      address: 'г. Могилёв, ул. Крупской, д. 15, кв. 6',
      website: 'grigorieva2.by',
      isAdmin: false,
      organization: 'ЧУП «МогилёвМедиа»',
      pass: null,
    },
    {
      uuid: '3b3a4f1c-9e4a-4f8a-a3b2-1c8d9e2f4a6b',
      fullName: 'Александр Иванов',
      login: 'alex_ivanov',
      address: 'г. Минск, пр. Независимости, д. 45, кв. 12',
      website: 'ivanov.by',
      isAdmin: false,
      organization: 'ООО «БелТех»',
      pass: null,
    },
    {
      uuid: '8f2e5d1c-7a3b-4c9e-8f1a-2b3c4d5e6f7a',
      fullName: 'Дмитрий Петров',
      login: 'dmitry_p',
      address: 'г. Гомель, ул. Советская, д. 10, кв. 5',
      website: 'petrov.dev',
      isAdmin: false,
      organization: 'ЧУП «ГомельПром»',
      pass: null,
    },
    {
      uuid: '1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d',
      fullName: 'Мария Козлова',
      login: 'maria_koz',
      address: 'г. Витебск, ул. Ленина, д. 7, кв. 3',
      website: 'kozlova.by',
      isAdmin: false,
      organization: 'РУП «ВитебскСвязь»',
      pass: null,
    },
    {
      uuid: '9e8d7c6b-5a4f-3e2d-1c0b-9a8f7e6d5c4b',
      fullName: 'Елена Новикова',
      login: 'elena_nov',
      address: 'г. Могилёв, пр. Мира, д. 22, кв. 8',
      website: 'novikova.net',
      isAdmin: false,
      organization: 'ООО «МогилёвЛогистик»',
      pass: null,
    },
    {
      uuid: 'd4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a',
      fullName: 'Сергей Волков',
      login: 'sergey_v',
      address: 'г. Гродно, ул. Ожешко, д. 15, кв. 11',
      website: 'volkov.by',
      isAdmin: false,
      organization: 'СООО «ГродноСтрой»',
      pass: null,
    },
    {
      uuid: 'b3c4d5e6-f7a8-9b0c-1d2e-3f4a5b6c7d8e',
      fullName: 'Анна Соколова',
      login: 'anna_sok',
      address: 'г. Брест, пр. Машерова, д. 30, кв. 4',
      website: 'sokolova.by',
      isAdmin: false,
      organization: 'ИП Соколова А.В.',
      pass: null,
    },
    {
      uuid: 'c5d6e7f8-a9b0-1c2d-3e4f-5a6b7c8d9e0f',
      fullName: 'Павел Морозов',
      login: 'pavel_m',
      address: 'г. Минск, ул. Кальварийская, д. 55, кв. 9',
      website: 'morozov.tech',
      isAdmin: false,
      organization: 'ООО «МинскИТ»',
      pass: null,
    },
    {
      uuid: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      fullName: 'Ольга Лебедева',
      login: 'olga_leb',
      address: 'г. Барановичи, ул. Гагарина, д. 12, кв. 2',
      website: 'lebedeva.by',
      isAdmin: false,
      organization: 'ЧУП «БарановичиТекс»',
      pass: null,
    },
    {
      uuid: 'b2c3d4e5-f6a7-8901-bcde-f23456789012',
      fullName: 'Виктор Кузнецов',
      login: 'viktor_k',
      address: 'г. Бобруйск, ул. Минская, д. 8, кв. 15',
      website: 'kuznetsov.by',
      isAdmin: false,
      organization: 'РУП «БобруйскМаш»',
      pass: null,
    },
    {
      uuid: 'c3d4e5f6-a7b8-9012-cdef-345678901234',
      fullName: 'Татьяна Попова',
      login: 'tanya_p',
      address: 'г. Пинск, ул. Ленина, д. 33, кв. 6',
      website: 'popova.by',
      isAdmin: false,
      organization: 'ООО «ПинскАгро»',
      pass: null,
    },
    {
      uuid: 'd4e5f6a7-b8c9-0123-def0-456789012345',
      fullName: 'Андрей Смирнов',
      login: 'andrey_sm',
      address: 'г. Минск, ул. Сурганова, д. 18, кв. 21',
      website: 'smirnov.dev',
      isAdmin: false,
      organization: 'СЗАО «БелТелеком»',
      pass: null,
    },
    {
      uuid: 'e5f6a7b8-c9d0-1234-ef01-567890123456',
      fullName: 'Наталья Васильева',
      login: 'nata_v',
      address: 'г. Гомель, ул. Хлеборобов, д. 4, кв. 7',
      website: 'vasilieva.by',
      isAdmin: false,
      organization: 'ЧУП «ГомельФуд»',
      pass: null,
    },
    {
      uuid: 'f6a7b8c9-d0e1-2345-f012-678901234567',
      fullName: 'Игорь Зайцев',
      login: 'igor_z',
      address: 'г. Витебск, пр. Фрунзе, д. 50, кв. 14',
      website: 'zaytsev.by',
      isAdmin: false,
      organization: 'ООО «ВитебскЭнерго»',
      pass: null,
    },
    {
      uuid: 'a7b8c9d0-e1f2-3456-0123-789012345678',
      fullName: 'Светлана Павлова',
      login: 'sveta_p',
      address: 'г. Могилёв, ул. Крупской, д. 9, кв. 3',
      website: 'pavlova.by',
      isAdmin: false,
      organization: 'РУП «МогилёвХим»',
      pass: null,
    },
    {
      uuid: 'b8c9d0e1-f2a3-4567-1234-890123456789',
      fullName: 'Роман Егоров',
      login: 'roman_e',
      address: 'г. Гродно, ул. Горького, д. 25, кв. 19',
      website: 'egorov.net',
      isAdmin: false,
      organization: 'СООО «ГродноМедиа»',
      pass: null,
    },
    {
      uuid: 'c9d0e1f2-a3b4-5678-2345-901234567890',
      fullName: 'Юлия Николаева',
      login: 'yulia_n',
      address: 'г. Брест, ул. Московская, д. 11, кв. 8',
      website: 'nikolaeva.by',
      isAdmin: false,
      organization: 'ИП Николаева Ю.С.',
      pass: null,
    },
    {
      uuid: 'd0e1f2a3-b4c5-6789-3456-012345678901',
      fullName: 'Максим Андреев',
      login: 'max_a',
      address: 'г. Минск, пр. Дзержинского, д. 70, кв. 22',
      website: 'andreev.by',
      isAdmin: false,
      organization: 'ООО «МинскСтрой»',
      pass: null,
    },
    {
      uuid: 'e1f2a3b4-c5d6-7890-4567-123456789012',
      fullName: 'Дарья Михайлова',
      login: 'daria_m',
      address: 'г. Борисов, ул. Чапаева, д. 6, кв. 5',
      website: 'mikhailova.by',
      isAdmin: false,
      organization: 'ЧУП «БорисовПласт»',
      pass: null,
    },
    {
      uuid: 'f2a3b4c5-d6e7-8901-5678-234567890123',
      fullName: 'Артем Степанов',
      login: 'artem_s',
      address: 'г. Минск, ул. Богдановича, д. 35, кв. 17',
      website: 'stepanov.dev',
      isAdmin: false,
      organization: 'ООО «ТехноБел»',
      pass: null,
    },
    {
      uuid: 'a3b4c5d6-e7f8-9012-6789-345678901234',
      fullName: 'Ксения Макарова',
      login: 'ksenia_m',
      address: 'г. Гомель, ул. Ильича, д. 28, кв. 10',
      website: 'makarova.by',
      isAdmin: false,
      organization: 'РУП «ГомельСвет»',
      pass: null,
    },
    {
      uuid: 'b4c5d6e7-f8a9-0123-7890-456789012345',
      fullName: 'Никита Федоров',
      login: 'nikita_f',
      address: 'г. Витебск, ул. Замковая, д. 14, кв. 4',
      website: 'fedorov.by',
      isAdmin: false,
      organization: 'СООО «ВитебскЛогистик»',
      pass: null,
    },
    {
      uuid: 'c5d6e7f8-a9b0-1234-8901-567890123456',
      fullName: 'Валерия Денисова',
      login: 'valeria_d',
      address: 'г. Могилёв, пр. Шмидта, д. 19, кв. 6',
      website: 'denisova.by',
      isAdmin: false,
      organization: 'ООО «МогилёвФарм»',
      pass: null,
    },
    {
      uuid: 'd6e7f8a9-b0c1-2345-9012-678901234567',
      fullName: 'Кирилл Алексеев',
      login: 'kirill_a',
      address: 'г. Гродно, ул. Дубко, д. 41, кв. 13',
      website: 'alekseev.by',
      isAdmin: false,
      organization: 'ЧУП «ГродноАгро»',
      pass: null,
    },
    {
      uuid: 'e7f8a9b0-c1d2-3456-0123-789012345678',
      fullName: 'Полина Сорокина',
      login: 'polina_s',
      address: 'г. Брест, пр. Партизанский, д. 22, кв. 9',
      website: 'sorokina.by',
      isAdmin: false,
      organization: 'ИП Сорокина П.А.',
      pass: null,
    },
    {
      uuid: 'f8a9b0c1-d2e3-4567-1234-890123456789',
      fullName: 'Владислав Григорьев',
      login: 'vlad_g',
      address: 'г. Минск, ул. Притыцкого, д. 60, кв. 15',
      website: 'grigoriev.by',
      isAdmin: false,
      organization: 'ООО «МинскТранс»',
      pass: null,
    },
    {
      uuid: 'a9b0c1d2-e3f4-5678-2345-901234567890',
      fullName: 'Алина Романова',
      login: 'alina_r',
      address: 'г. Барановичи, ул. Тельмана, д. 7, кв. 11',
      website: 'romanova.by',
      isAdmin: false,
      organization: 'РУП «БарановичиСвязь»',
      pass: null,
    },
    {
      uuid: 'b0c1d2e3-f4a5-6789-3456-012345678901',
      fullName: 'Тимур Козлов',
      login: 'timur_k',
      address: 'г. Бобруйск, ул. Социалистическая, д. 16, кв. 3',
      website: 'kozlov.by',
      isAdmin: false,
      organization: 'СЗАО «БобруйскИнвест»',
      pass: null,
    },
    {
      uuid: 'c1d2e3f4-a5b6-7890-4567-123456789012',
      fullName: 'Вероника Ефимова',
      login: 'veronika_e',
      address: 'г. Пинск, ул. Заслонова, д. 9, кв. 7',
      website: 'efimova.by',
      isAdmin: false,
      organization: 'ООО «ПинскТекстиль»',
      pass: null,
    },
    {
      uuid: 'd2e3f4a5-b6c7-8901-5678-234567890123',
      fullName: 'Даниил Орлов',
      login: 'daniil_o',
      address: 'г. Минск, пр. Независимости, д. 88, кв. 20',
      website: 'orlov.dev',
      isAdmin: false,
      organization: 'ЧУП «МинскДизайн»',
      pass: null,
    },
    {
      uuid: 'e3f4a5b6-c7d8-9012-6789-345678901234',
      fullName: 'Ева Жукова',
      login: 'eva_zh',
      address: 'г. Гомель, ул. Барыкина, д. 5, кв. 4',
      website: 'zhukova.by',
      isAdmin: false,
      organization: 'РУП «ГомельМаш»',
      pass: null,
    },
    {
      uuid: 'f4a5b6c7-d8e9-0123-7890-456789012345',
      fullName: 'Глеб Савельев',
      login: 'gleb_s',
      address: 'г. Витебск, ул. Чкалова, д. 27, кв. 12',
      website: 'saveliev.by',
      isAdmin: false,
      organization: 'ООО «ВитебскПрод»',
      pass: null,
    },
    {
      uuid: 'a5b6c7d8-e9f0-1234-8901-567890123456',
      fullName: 'Ульяна Козлова',
      login: 'ulyana_k',
      address: 'г. Могилёв, ул. Челюскинцев, д. 34, кв. 8',
      website: 'kozlova2.by',
      isAdmin: false,
      organization: 'СООО «МогилёвСтрой»',
      pass: null,
    },
    {
      uuid: 'b6c7d8e9-f0a1-2345-9012-678901234567',
      fullName: 'Марк Белов',
      login: 'mark_b',
      address: 'г. Гродно, пр. Янки Купалы, д. 10, кв. 16',
      website: 'belov.by',
      isAdmin: false,
      organization: 'ИП Белов М.Д.',
      pass: null,
    },
    {
      uuid: 'c7d8e9f0-a1b2-3456-0123-789012345678',
      fullName: 'Милана Воронина',
      login: 'milana_v',
      address: 'г. Брест, ул. Ленина, д. 55, кв. 2',
      website: 'voronina.by',
      isAdmin: false,
      organization: 'ООО «БрестЛогистик»',
      pass: null,
    },
    {
      uuid: 'd8e9f0a1-b2c3-4567-1234-890123456789',
      fullName: 'Лев Тихонов',
      login: 'lev_t',
      address: 'г. Минск, ул. Кирова, д. 42, кв. 7',
      website: 'tikhonov.by',
      isAdmin: false,
      organization: 'ЧУП «МинскМедиа»',
      pass: null,
    },
    {
      uuid: 'e9f0a1b2-c3d4-5678-2345-901234567890',
      fullName: 'Арина Морозова',
      login: 'arina_m',
      address: 'г. Борисов, ул. Крупской, д. 13, кв. 5',
      website: 'morozova2.by',
      isAdmin: false,
      organization: 'РУП «БорисовХим»',
      pass: null,
    },
    {
      uuid: 'f0a1b2c3-d4e5-6789-3456-012345678901',
      fullName: 'Матвей Дмитриев',
      login: 'matvey_d',
      address: 'г. Минск, пр. Победителей, д. 90, кв. 14',
      website: 'dmitriev.by',
      isAdmin: false,
      organization: 'ООО «МинскФуд»',
      pass: null,
    },
    {
      uuid: 'a1b2c3d4-e5f6-7890-4567-123456789abc',
      fullName: 'Серафима Ильина',
      login: 'sera_i',
      address: 'г. Гомель, ул. Речицкая, д. 21, кв. 9',
      website: 'ilina.by',
      isAdmin: false,
      organization: 'СЗАО «ГомельПроект»',
      pass: null,
    },
    {
      uuid: 'b2c3d4e5-f6a7-8901-5678-234567890bcd',
      fullName: 'Захар Соловьев',
      login: 'zakhar_s',
      address: 'г. Витебск, ул. Ленина, д. 66, кв. 11',
      website: 'soloviev.by',
      isAdmin: false,
      organization: 'ЧУП «ВитебскТех»',
      pass: null,
    },
    {
      uuid: 'c3d4e5f6-a7b8-9012-6789-345678901cde',
      fullName: 'Аделина Фролова',
      login: 'adelina_f',
      address: 'г. Могилёв, пр. Мира, д. 48, кв. 3',
      website: 'frolova.by',
      isAdmin: false,
      organization: 'ООО «МогилёвТранс»',
      pass: null,
    },
    {
      uuid: 'd4e5f6a7-b8c9-0123-7890-456789012def',
      fullName: 'Тимофей Власов',
      login: 'timofey_v',
      address: 'г. Гродно, ул. Советская, д. 19, кв. 8',
      website: 'vlasov.by',
      isAdmin: false,
      organization: 'ИП Власов Т.А.',
      pass: null,
    },
    {
      uuid: 'e5f6a7b8-c9d0-1234-8901-567890123ef0',
      fullName: 'Елизавета Комарова',
      login: 'liza_k',
      address: 'г. Брест, пр. Машерова, д. 77, кв. 5',
      website: 'komarova.by',
      isAdmin: false,
      organization: 'РУП «БрестСвязь»',
      pass: null,
    },
    {
      uuid: 'f6a7b8c9-d0e1-2345-9012-678901234f01',
      fullName: 'Егор Новиков',
      login: 'egor_n',
      address: 'г. Минск, ул. Беды, д. 25, кв. 18',
      website: 'novikov2.by',
      isAdmin: false,
      organization: 'ООО «МинскАгро»',
      pass: null,
    },
    {
      uuid: 'a7b8c9d0-e1f2-3456-0123-789012345a12',
      fullName: 'Агата Кузнецова',
      login: 'agata_k',
      address: 'г. Барановичи, пр. Советский, д. 33, кв. 12',
      website: 'kuznetsova.by',
      isAdmin: false,
      organization: 'ЧУП «БарановичиПром»',
      pass: null,
    },
    {
      uuid: 'b8c9d0e1-f2a3-4567-1234-890123456b23',
      fullName: 'Савва Попов',
      login: 'savva_p',
      address: 'г. Бобруйск, ул. Минская, д. 50, кв. 7',
      website: 'popov2.by',
      isAdmin: false,
      organization: 'СООО «БобруйскСтрой»',
      pass: null,
    },
    {
      uuid: 'c9d0e1f2-a3b4-5678-2345-901234567c34',
      fullName: 'Таисия Лебедева',
      login: 'taisiya_l',
      address: 'г. Пинск, ул. Ленина, д. 44, кв. 15',
      website: 'lebedeva2.by',
      isAdmin: false,
      organization: 'ООО «ПинскЛогистик»',
      pass: null,
    },
    {
      uuid: 'd0e1f2a3-b4c5-6789-3456-012345678d45',
      fullName: 'Всеволод Семенов',
      login: 'vsevolod_s',
      address: 'г. Минск, ул. Сурганова, д. 12, кв. 9',
      website: 'semenov.by',
      isAdmin: false,
      organization: 'РУП «МинскЭнерго»',
      pass: null,
    },
    {
      uuid: 'e1f2a3b4-c5d6-7890-4567-123456789e56',
      fullName: 'Варвара Орлова',
      login: 'varvara_o',
      address: 'г. Гомель, ул. Хлеборобов, д. 29, кв. 4',
      website: 'orlova.by',
      isAdmin: false,
      organization: 'ИП Орлова В.С.',
      pass: null,
    },
  ],
};

const setCustomTimeout = (cb) => {
  const delays = [0, 500, 1000, 1500, 2000, 2500, 3000, 4000, 5000];
  const delay = delays[Math.floor(Math.random() * delays.length)];
  return setTimeout(() => {
    cb?.();
  }, delay);
};

app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
  if (req.method === 'OPTIONS') {
    return res.sendStatus(200);
  }
  next();
});

app.use((req, res, next) => {
  if (typeof req.body === 'string' && req.body.length > 0) {
    try {
      req.body = JSON.parse(req.body);
    } catch (e) {}
  }
  next();
});

app.post('/api/login', (req, res) => {
  setCustomTimeout(() => {
    const { login, pass } = req.body;

    const findetUser = DATA.users.find((user) => user.login === login && user.pass === pass);
    if (findetUser) {
      const { pass, ...userWithoutPass } = findetUser;
      res.json({
        data: userWithoutPass,
      });
    } else {
      res.status(404).send(JSON.stringify('Не зареган'));
    }
  });
});

app.get('/api/users', (_, res) => {
  setCustomTimeout(() => {
    res.json({
      data: DATA.users,
    });
  });
});

app.listen(PORT, () => {
  console.log(`listen on port ${PORT}`);
});
